package policy

import (
	"fmt"
	"path/filepath"
	"strings"
)

// EgressProxyImage is the locally-built image used for egress proxy containers.
// Built from EgressProxyBaseImage during first use (see EgressProxyDockerfile).
const EgressProxyImage = "conga-egress-proxy"

// EgressProxyBaseImage is the Envoy image used as the base for the egress proxy.
// Envoy handles HTTP CONNECT tunneling with Lua-based domain filtering.
const EgressProxyBaseImage = "envoyproxy/envoy:v1.32-latest"

// EgressProxyDockerfile returns the Dockerfile content for building the egress proxy image.
func EgressProxyDockerfile() string {
	return "FROM " + EgressProxyBaseImage + "\n"
}

// LoadEgressPolicy loads the policy file, merges for the given agent, and returns
// the effective egress policy. Returns nil, nil if no policy file or no egress section.
func LoadEgressPolicy(policyDir string, agentName string) (*EgressPolicy, error) {
	policyPath := filepath.Join(policyDir, "conga-policy.yaml")
	pf, err := Load(policyPath)
	if err != nil {
		return nil, fmt.Errorf("loading policy: %w", err)
	}
	if pf == nil {
		return nil, nil
	}
	if err := pf.Validate(); err != nil {
		return nil, fmt.Errorf("invalid policy: %w", err)
	}

	effective := pf.MergeForAgent(agentName)
	return effective.Egress, nil
}

// EffectiveAllowedDomains returns the list of domains an agent can reach,
// excluding any that appear in blocked_domains. Blocked takes precedence.
func EffectiveAllowedDomains(e *EgressPolicy) []string {
	if e == nil || len(e.AllowedDomains) == 0 {
		return nil
	}
	blocked := make(map[string]bool, len(e.BlockedDomains))
	for _, d := range e.BlockedDomains {
		blocked[strings.ToLower(d)] = true
	}
	var result []string
	for _, d := range e.AllowedDomains {
		if !blocked[strings.ToLower(d)] {
			result = append(result, d)
		}
	}
	return result
}

// EgressProxyName returns the proxy container name for an agent.
func EgressProxyName(agentName string) string {
	return "conga-egress-" + agentName
}

// GenerateProxyConf generates an Envoy config for an egress proxy with domain filtering.
// Envoy handles HTTP CONNECT tunneling via its dynamic forward proxy filter.
// Domain filtering uses a Lua filter that inspects :authority before routing.
// When domains is non-empty, only listed domains pass through (allowlist mode).
// When domains is nil/empty, all traffic passes through (passthrough mode).
//
// NOTE: The bash reimplementation in terraform/user-data.sh.tftpl generates the same
// config format — keep both in sync when modifying.
func GenerateProxyConf(domains []string) string {
	var b strings.Builder

	b.WriteString("# Conga Line Egress Proxy — Envoy forward proxy with domain filtering\n")
	b.WriteString("# Generated by conga — do not edit manually\n")
	b.WriteString("static_resources:\n")
	b.WriteString("  listeners:\n")
	b.WriteString("  - address:\n")
	b.WriteString("      socket_address: { address: 0.0.0.0, port_value: 3128 }\n")
	b.WriteString("    filter_chains:\n")
	b.WriteString("    - filters:\n")
	b.WriteString("      - name: envoy.filters.network.http_connection_manager\n")
	b.WriteString("        typed_config:\n")
	b.WriteString("          \"@type\": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\n")
	b.WriteString("          stat_prefix: egress\n")
	b.WriteString("          http_protocol_options: {}\n")
	b.WriteString("          upgrade_configs:\n")
	b.WriteString("          - upgrade_type: CONNECT\n")
	b.WriteString("          route_config:\n")
	b.WriteString("            virtual_hosts:\n")
	b.WriteString("            - name: all\n")
	b.WriteString("              domains: [\"*\"]\n")
	b.WriteString("              routes:\n")
	b.WriteString("              - match: { connect_matcher: {} }\n")
	b.WriteString("                route:\n")
	b.WriteString("                  cluster: dynamic_forward_proxy\n")
	b.WriteString("                  upgrade_configs:\n")
	b.WriteString("                  - upgrade_type: CONNECT\n")
	b.WriteString("                    connect_config: {}\n")
	b.WriteString("              - match: { prefix: \"/\" }\n")
	b.WriteString("                route: { cluster: dynamic_forward_proxy }\n")
	b.WriteString("          http_filters:\n")

	// Lua domain filter — only emitted in allowlist mode.
	if len(domains) > 0 {
		b.WriteString("          - name: envoy.filters.http.lua\n")
		b.WriteString("            typed_config:\n")
		b.WriteString("              \"@type\": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua\n")
		b.WriteString("              default_source_code:\n")
		b.WriteString("                inline_string: |\n")
		b.WriteString("                  local EXACT = {\n")

		// Separate exact domains and wildcard suffixes.
		var suffixes []string
		for _, d := range domains {
			d = strings.ToLower(d)
			if base, ok := strings.CutPrefix(d, "*."); ok {
				suffixes = append(suffixes, base)
			} else {
				b.WriteString(fmt.Sprintf("                    [\"%s\"] = true,\n", d))
			}
		}
		b.WriteString("                  }\n")
		b.WriteString("                  local SUFFIXES = {\n")
		for _, s := range suffixes {
			b.WriteString(fmt.Sprintf("                    \".%s\",\n", s))
		}
		b.WriteString("                  }\n")
		b.WriteString("                  function envoy_on_request(h)\n")
		b.WriteString("                    local a = h:headers():get(\":authority\") or \"\"\n")
		b.WriteString("                    local host = a:match(\"^([^:]+)\"):lower()\n")
		b.WriteString("                    if EXACT[host] then return end\n")
		b.WriteString("                    for _, s in ipairs(SUFFIXES) do\n")
		b.WriteString("                      if host == s:sub(2) or host:sub(-#s) == s then return end\n")
		b.WriteString("                    end\n")
		b.WriteString("                    h:respond({[\":status\"] = \"403\"}, \"egress denied: \" .. host .. \"\\n\")\n")
		b.WriteString("                  end\n")
	}

	b.WriteString("          - name: envoy.filters.http.dynamic_forward_proxy\n")
	b.WriteString("            typed_config:\n")
	b.WriteString("              \"@type\": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig\n")
	b.WriteString("              dns_cache_config:\n")
	b.WriteString("                name: dns_cache\n")
	b.WriteString("                dns_lookup_family: V4_ONLY\n")
	b.WriteString("          - name: envoy.filters.http.router\n")
	b.WriteString("            typed_config:\n")
	b.WriteString("              \"@type\": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\n")

	b.WriteString("  clusters:\n")
	b.WriteString("  - name: dynamic_forward_proxy\n")
	b.WriteString("    lb_policy: CLUSTER_PROVIDED\n")
	b.WriteString("    cluster_type:\n")
	b.WriteString("      name: envoy.clusters.dynamic_forward_proxy\n")
	b.WriteString("      typed_config:\n")
	b.WriteString("        \"@type\": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig\n")
	b.WriteString("        dns_cache_config:\n")
	b.WriteString("          name: dns_cache\n")
	b.WriteString("          dns_lookup_family: V4_ONLY\n")

	return b.String()
}

// GenerateProxyEntrypoint returns a shell entrypoint script for the egress proxy container.
func GenerateProxyEntrypoint() string {
	return `#!/bin/sh
exec envoy -c /etc/envoy/envoy.yaml --log-level warn
`
}

// ProxyBootstrapJS returns a Node.js script that patches fetch() and https.globalAgent
// to route all HTTP(S) traffic through the egress proxy. Without this, Node.js ignores
// the HTTPS_PROXY env var — fetch() doesn't honor it, and axios's built-in proxy
// support uses regular HTTP requests instead of CONNECT tunneling (which breaks tinyproxy).
//
// The bootstrap script:
//  1. Sets undici's EnvHttpProxyAgent as the global fetch dispatcher
//  2. Replaces https.globalAgent with a CONNECT tunnel agent (pure built-in modules)
//  3. Saves the proxy URL in __CONGA_PROXY_URL so child processes can re-discover it
//  4. Deletes standard proxy env vars so axios falls back to globalAgent instead of its broken proxy
//
// Injected via NODE_OPTIONS="--require /opt/proxy-bootstrap.js" in the container.
func ProxyBootstrapJS() string {
	return `// Conga Line egress proxy bootstrap — patches Node.js to route through HTTPS_PROXY
// Loaded via NODE_OPTIONS="--require ..." before the application starts.
'use strict';
const proxyUrl = process.env.HTTPS_PROXY || process.env.HTTP_PROXY || process.env.__CONGA_PROXY_URL;
if (proxyUrl) {
  const http = require('http');
  const https = require('https');
  const tls = require('tls');
  const { URL } = require('url');

  if (!process.env.HTTPS_PROXY) process.env.HTTPS_PROXY = proxyUrl;
  const { EnvHttpProxyAgent, setGlobalDispatcher } = require('/app/node_modules/undici');
  setGlobalDispatcher(new EnvHttpProxyAgent());

  const parsed = new URL(proxyUrl);
  class ConnectProxyAgent extends https.Agent {
    constructor() {
      super({ keepAlive: true });
    }
    createConnection(opts, cb) {
      const req = http.request({
        host: parsed.hostname,
        port: parsed.port,
        method: 'CONNECT',
        path: (opts.host || opts.hostname) + ':' + (opts.port || 443),
      });
      req.on('connect', (_res, socket) => {
        if (_res.statusCode !== 200) {
          cb(new Error('Proxy CONNECT failed: ' + _res.statusCode));
          return;
        }
        const tlsSock = tls.connect({
          socket: socket,
          servername: opts.host || opts.hostname,
        }, () => cb(null, tlsSock));
        tlsSock.on('error', cb);
      });
      req.on('error', cb);
      req.end();
    }
  }
  https.globalAgent = new ConnectProxyAgent();

  process.env.__CONGA_PROXY_URL = proxyUrl;
  process.env.HTTPS_PROXY = proxyUrl;
  process.env.HTTP_PROXY = proxyUrl;
}
`
}
