package policy

import (
	"fmt"
	"path/filepath"
	"strings"
)

// EgressProxyImage is the pinned nginx image used for egress proxy containers.
// Pinned for reproducibility and supply chain safety.
const EgressProxyImage = "nginx:1.27-alpine"

// LoadEgressPolicy loads the policy file, merges for the given agent, and returns
// the effective egress policy. Returns nil, nil if no policy file or no egress section.
func LoadEgressPolicy(policyDir string, agentName string) (*EgressPolicy, error) {
	policyPath := filepath.Join(policyDir, "conga-policy.yaml")
	pf, err := Load(policyPath)
	if err != nil {
		return nil, fmt.Errorf("loading policy: %w", err)
	}
	if pf == nil {
		return nil, nil
	}
	if err := pf.Validate(); err != nil {
		return nil, fmt.Errorf("invalid policy: %w", err)
	}

	effective := pf.MergeForAgent(agentName)
	return effective.Egress, nil
}

// EffectiveAllowedDomains returns the list of domains an agent can reach,
// excluding any that appear in blocked_domains. Blocked takes precedence.
func EffectiveAllowedDomains(e *EgressPolicy) []string {
	if e == nil || len(e.AllowedDomains) == 0 {
		return nil
	}
	blocked := make(map[string]bool, len(e.BlockedDomains))
	for _, d := range e.BlockedDomains {
		blocked[strings.ToLower(d)] = true
	}
	var result []string
	for _, d := range e.AllowedDomains {
		if !blocked[strings.ToLower(d)] {
			result = append(result, d)
		}
	}
	return result
}

// EgressProxyName returns the proxy container name for an agent.
func EgressProxyName(agentName string) string {
	return "conga-egress-" + agentName
}

// GenerateNginxConf generates the full nginx.conf for an egress proxy with domain filtering.
// When domains is non-empty, only listed domains pass through (allowlist mode).
// When domains is nil/empty, all traffic passes through (passthrough mode).
func GenerateNginxConf(domains []string) string {
	var b strings.Builder

	b.WriteString("# Conga Line Egress Proxy — per-agent domain filtering\n")
	b.WriteString("# Generated by conga — do not edit manually\n\n")
	b.WriteString("events {\n    worker_connections 256;\n}\n\n")
	b.WriteString("stream {\n")

	// Log format for denied connections (empty upstream = denied)
	b.WriteString("    log_format egress '$remote_addr [$time_local] '\n")
	b.WriteString("                      '$ssl_preread_server_name -> $upstream '\n")
	b.WriteString("                      '$status $bytes_sent $bytes_received';\n")
	b.WriteString("    access_log /dev/stdout egress;\n\n")

	if len(domains) > 0 {
		// Allowlist mode: only listed domains pass
		b.WriteString("    map $ssl_preread_server_name $upstream {\n")
		b.WriteString("        default \"\";\n")
		for _, d := range domains {
			d = strings.ToLower(d)
			if base, ok := strings.CutPrefix(d, "*."); ok {
				escaped := strings.ReplaceAll(base, ".", "\\.")
				b.WriteString(fmt.Sprintf("        \"~^.+\\.%s$\" $ssl_preread_server_name:443;\n", escaped))
			} else {
				b.WriteString(fmt.Sprintf("        %s %s:443;\n", d, d))
			}
		}
		b.WriteString("    }\n\n")
	} else {
		// Passthrough mode: all domains pass
		b.WriteString("    map $ssl_preread_server_name $upstream {\n")
		b.WriteString("        default $ssl_preread_server_name:443;\n")
		b.WriteString("    }\n\n")
	}

	// HTTPS proxy — uses Docker's embedded DNS (127.0.0.11) for resolution.
	// No DNS forwarding listener — avoids DNS tunneling exfiltration vector.
	b.WriteString("    server {\n")
	b.WriteString("        listen 3128;\n")
	b.WriteString("        proxy_pass $upstream;\n")
	b.WriteString("        ssl_preread on;\n")
	b.WriteString("        resolver 127.0.0.11 valid=300s;\n")
	b.WriteString("        resolver_timeout 5s;\n")
	b.WriteString("    }\n")

	b.WriteString("}\n")
	return b.String()
}
