package policy

import (
	"fmt"
	"path/filepath"
	"strings"
)

// EgressProxyImage is the locally-built image used for egress proxy containers.
// Built from EgressProxyBaseImage during first use (see EgressProxyDockerfile).
const EgressProxyImage = "conga-egress-proxy"

// EgressProxyBaseImage is the base image for building the egress proxy.
// Pinned for reproducibility and supply chain safety.
const EgressProxyBaseImage = "alpine:3.21"

// EgressProxyDockerfile returns the Dockerfile content for building the egress proxy image.
func EgressProxyDockerfile() string {
	return "FROM " + EgressProxyBaseImage + "\nRUN apk add --no-cache squid >/dev/null 2>&1\n"
}

// LoadEgressPolicy loads the policy file, merges for the given agent, and returns
// the effective egress policy. Returns nil, nil if no policy file or no egress section.
func LoadEgressPolicy(policyDir string, agentName string) (*EgressPolicy, error) {
	policyPath := filepath.Join(policyDir, "conga-policy.yaml")
	pf, err := Load(policyPath)
	if err != nil {
		return nil, fmt.Errorf("loading policy: %w", err)
	}
	if pf == nil {
		return nil, nil
	}
	if err := pf.Validate(); err != nil {
		return nil, fmt.Errorf("invalid policy: %w", err)
	}

	effective := pf.MergeForAgent(agentName)
	return effective.Egress, nil
}

// EffectiveAllowedDomains returns the list of domains an agent can reach,
// excluding any that appear in blocked_domains. Blocked takes precedence.
func EffectiveAllowedDomains(e *EgressPolicy) []string {
	if e == nil || len(e.AllowedDomains) == 0 {
		return nil
	}
	blocked := make(map[string]bool, len(e.BlockedDomains))
	for _, d := range e.BlockedDomains {
		blocked[strings.ToLower(d)] = true
	}
	var result []string
	for _, d := range e.AllowedDomains {
		if !blocked[strings.ToLower(d)] {
			result = append(result, d)
		}
	}
	return result
}

// EgressProxyName returns the proxy container name for an agent.
func EgressProxyName(agentName string) string {
	return "conga-egress-" + agentName
}

// GenerateProxyConf generates a Squid config for an egress proxy with domain filtering.
// Squid handles HTTP CONNECT tunneling natively, which is required because
// HTTPS_PROXY=http://... causes clients to send HTTP CONNECT requests.
// When domains is non-empty, only listed domains pass through (allowlist mode).
// When domains is nil/empty, all traffic passes through (passthrough mode).
//
// NOTE: The bash reimplementation in terraform/user-data.sh.tftpl generates the same
// config format — keep both in sync when modifying.
func GenerateProxyConf(domains []string) string {
	var b strings.Builder

	b.WriteString("# Conga Line Egress Proxy — per-agent domain filtering\n")
	b.WriteString("# Generated by conga — do not edit manually\n\n")
	b.WriteString("http_port 3128\n\n")

	if len(domains) > 0 {
		// Allowlist mode: only listed domains pass
		b.WriteString("acl allowed_domains dstdomain")
		for _, d := range domains {
			d = strings.ToLower(d)
			if base, ok := strings.CutPrefix(d, "*."); ok {
				// *.example.com → .example.com (Squid matches all subdomains)
				b.WriteString(fmt.Sprintf(" .%s", base))
			} else {
				b.WriteString(fmt.Sprintf(" %s", d))
			}
		}
		b.WriteString("\n\n")

		b.WriteString("acl SSL_ports port 443\n")
		b.WriteString("acl CONNECT method CONNECT\n")
		b.WriteString("http_access allow CONNECT allowed_domains SSL_ports\n")
		b.WriteString("http_access allow allowed_domains\n")
		b.WriteString("http_access deny all\n\n")
	} else {
		// Passthrough mode: all domains pass
		b.WriteString("http_access allow all\n\n")
	}

	b.WriteString("# Disable caching — proxy is for filtering only\n")
	b.WriteString("cache deny all\n\n")
	b.WriteString("# Log to stdout/stderr for Docker log collection\n")
	b.WriteString("access_log stdio:/dev/stdout\n")
	b.WriteString("cache_log stdio:/dev/stderr\n\n")
	b.WriteString("# Minimal resource usage\n")
	b.WriteString("workers 1\n")

	return b.String()
}
