package managedhost

import (
	"fmt"
	"strings"

	"github.com/cruxdigital-llc/conga-line/pkg/common"
)

// ReservedKeyGuardScript generates a small, self-contained shell guard that fails
// closed (exit 1) if any of the given $include layer files declares a Conga-owned
// reserved key (the channel allowlist / gateway / plugins / a nested $include). It
// is wired as a systemd ExecStartPre so a reserved-key violation PREVENTS the agent
// from starting — stopping channel-allowlist escalation from ever taking effect
// (the prevention-first integrity model; spec §8). This replaces the periodic,
// after-the-fact reserved-key alarm with a start-time gate.
//
// The reserved-key list is rendered from common.ReservedCustomConfigKeys, so the
// host guard cannot drift from the Go validator (single source of truth).
//
// On an unparseable (JSON5) include the guard logs a WARN and ALLOWS start: it
// can't verify, but on managed hosts the include files are root:root 0444 (uid 1000
// cannot inject), so an unparseable file is an admin/root artifact, not an
// agent-injection vector (spec §8, the documented residual).
func ReservedKeyGuardScript(includePaths []string) string {
	quoted := make([]string, 0, len(common.ReservedCustomConfigKeys))
	for _, k := range common.ReservedCustomConfigKeys {
		// Quote regex metacharacters; the only one in the reserved set is the
		// leading "$" of "$include".
		quoted = append(quoted, strings.NewReplacer("$", `\$`, ".", `\.`).Replace(k))
	}
	pattern := strings.Join(quoted, "|")

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# GENERATED by pkg/provider/managedhost (ReservedKeyGuardScript).\n")
	b.WriteString("# Fail-closed: refuses to start if any $include layer declares a Conga-owned key.\n")
	b.WriteString("# Key list is generated from common.ReservedCustomConfigKeys — do not hand-edit.\n")
	b.WriteString("set -u\n")
	for _, p := range includePaths {
		fmt.Fprintf(&b, "F=%q\n", p)
		b.WriteString("if [ -f \"$F\" ]; then\n")
		b.WriteString("  if KEYS=$(jq -r 'keys[]' \"$F\" 2>/dev/null); then\n")
		fmt.Fprintf(&b, "    if printf '%%s\\n' \"$KEYS\" | grep -Eqx '%s'; then\n", pattern)
		b.WriteString("      echo \"FATAL: $F declares a Conga-owned reserved key — refusing to start\" >&2\n")
		b.WriteString("      exit 1\n")
		b.WriteString("    fi\n")
		b.WriteString("  else\n")
		b.WriteString("    echo \"WARN: $F is not strict JSON (JSON5?); reserved-key check skipped (root:root 0444 perms compensate)\" >&2\n")
		b.WriteString("  fi\n")
		b.WriteString("fi\n")
	}
	b.WriteString("exit 0\n")
	return b.String()
}
